title: Isaac Lera 
description: Code recipes
author: Isaac Lera
avatar: /logo.png
email: isaac.lera \at uib \dot es
fitxaUIB: "University file"
fitxaUIBURL: https://personal.uib.es/isaac.lera
#baseurl: "/isaaclera"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

      
paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - UpdateLaWeb
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.png
social:
  name: Isaac Lera
  links:
    - https://www.uib.es/es/personal/ABTIxNTgx/
    - https://github.com/wisaaco
    - https://scholar.google.es/citations?user=cLVksYoAAAAJ&hl=es
    - http://orcid.org/0000-0002-2826-5970
    - https://www.researchgate.net/profile/Isaac_Lera
    - http://www.researcherid.com/rid/E-5467-2011
# google_site_verification: 
lang: es
